version: "3.3"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'freshshop'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped
  mongodb:
      image: mongo:latest
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: freshshop
      volumes:
        - ./docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/Dockerfile_nginx
    ports:
      - "8080:80"
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  server:
    container_name: server
    build:
      context: .
      dockerfile: docker/Dockerfile_server
    ports:
      - "3000:3000"
    command: sh -c "/wait && npm start"
    volumes:
        - ./server/src/:/usr/src/server/src
    environment:
      - WAIT_HOSTS=mysql:3307, mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=20
      - WAIT_HOST_CONNECT_TIMEOUT=30
  # client:
  #   container_name: client
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile_client
  #   volumes:
  #     - ./test/src/:/client/src
  #     - ./test/public/:/client/public
  #     - build:/client/build
