version: "3.3"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'freshshop'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped
  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    command: sh -c "/wait && cd server && npm run server"
    environment:
      - WAIT_HOSTS=mysql:3307
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=20
      - WAIT_HOST_CONNECT_TIMEOUT=30